services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  medical-api:
    build: .
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
